#!/bin/bash

# Help page
showHelp() {
    cat << EOF
Usage: ./sbsmtf -i <input-file> -o <output-directory> [--cores/--rank_min/--rank_max/--lambda_min/--lambda_max/--trials/--n_iter_max/--x_new_list/--input_sparse/--output_sparse/--x_new_sparse/--w_new_sparse/--bin_h/--bin_w_new/--beta/--ratio/--memgb/-h/-v]
Cross validation workflow of Semi-Binary Symmetric Matrix Tri-Factorization (SBSMTF)

    -i, -input,         --input                 Input file (e.g., data/testdata.tsv, mandatory)

    -o, -outdir,        --outdir                Output directory (e.g., output, mandatory)

    -c, -cores,         --cores                 Number of cores to use Snakemake (Default value is 10, optional)

    -l, -rank_min,      --rank_min              Lower limit of rank parameter to search (Default value is 2, which is used for the rank parameter J of dNMF, optional)

    -u, -rank_max,      --rank_max              Upper limit of rank parameter to search (Default value is 10, which is used for the rank parameter J of dNMF, optional)

    -b, -lambda_min,    --lambda_min            Lower limit of lambda parameter to search (Default value is 1, which means 10^1 is used for the binary regularization parameter Bin_U of dNMF, optional)

    -d, -lambda_max,    --lambda_max            Upper limit of lambda parameter to search (Default value is 10, which means 10^10 is used for the binary regularization parameter Bin_U of dNMF, optional)

    -t, -trials,        --trials                Number of random trials (Default value is 10, optional)

    -e, -n_iter_max,    --n_iter_max            Number of iterations (Default value is 100, optional)

    -x, -x_new_list,    --x_new_list            X_new file list to predict U_new values (Default value is "", which means no prediction is performed, optional)

    -s, -input_sparse,  --input_sparse          Whether the input data is formatted as Matrix Market <MM> (Default value is FALSE, optional)

    -f, -output_sparse, --output_sparse         Whether the output data is formatted as Matrix Market <MM> (Default value is FALSE, optional)

    -r, -x_new_sparse,  --x_new_sparse          Whether the X_new data is formatted as Matrix Market <MM> (Default value is FALSE, optional)

    -g, -w_new_sparse,  --w_new_sparse          Whether the W_new is formatted as Matrix Market <MM> (Default value is FALSE, optional)

    -n, -bin_h,         --bin_h                 Whether the binarization of H is perfomed (Default value is TRUE, optional)

    -w, -bin_w_new,     --bin_w_new             Whether the binarization of W_new is perfomed (Default value is FALSE, optional)

    -p, -beta,          --beta                  Parameter for Beta-divergence (Default value is 2, optional)

    -a, -ratio,         --ratio                 Sampling ratio of cross-validation (Default value is 20, optional)

    -m, -memgb,         --memgb                 Memory usage (GB, Default value is 10, optional)

    -h, -help,          --help                  Display help

    -v, -version,       --version               Version of this workflow

EOF
}

# Default Values
INPUT=""
OUTDIR=""
CORES=10
RANK_MIN=2
RANK_MAX=10
LAMBDA_MIN=1
LAMBDA_MAX=10
TRIALS=10
N_ITER_MAX=100
X_NEW_LIST="None"
INPUT_SPARSE="FALSE"
OUTPUT_SPARSE="FALSE"
X_NEW_SPARSE="FALSE"
W_NEW_SPARSE="FALSE"
BIN_H="TRUE"
BIN_W_NEW="FALSE"
BETA=2
RATIO=20
MEMGB=10
VERSION="v1.4.3"

# Command Argument Parsing
while getopts i:o:c:l:u:b:d:t:e:x:s:f:r:g:n:w:p:a:m:h-:v- opt; do
    optarg="$OPTARG"
    [[ "$opt" = - ]] &&
        opt="-${OPTARG%%=*}" &&
        optarg="${OPTARG/${OPTARG%%=*}/}" &&
        optarg="${optarg#=}"
    case "-$opt" in
        -i|--input)
            INPUT="$optarg"
            ;;
        -o|--outdir)
            OUTDIR="$optarg"
            ;;
        -c|--cores)
            CORES="$optarg"
            ;;
        -l|--rank_min)
            RANK_MIN="$optarg"
            ;;
        -u|--rank_max)
            RANK_MAX="$optarg"
            ;;
        -b|--lambda_min)
            LAMBDA_MIN="$optarg"
            ;;
        -d|--lambda_max)
            LAMBDA_MAX="$optarg"
            ;;
        -t|--trials)
            TRIALS="$optarg"
            ;;
        -e|--n_iter_max)
            N_ITER_MAX="$optarg"
            ;;
        -x|--x_new_list)
            X_NEW_LIST="$optarg"
            ;;
        -s|--input_sparse)
            INPUT_SPARSE="$optarg"
            ;;
        -f|--output_sparse)
            OUTPUT_SPARSE="$optarg"
            ;;
        -r|--x_new_sparse)
            X_NEW_SPARSE="$optarg"
            ;;
        -g|--w_new_sparse)
            W_NEW_SPARSE="$optarg"
            ;;
        -n|--bin_h)
            BIN_H="$optarg"
            ;;
        -w|--bin_w_new)
            BIN_W_NEW="$optarg"
            ;;
        -p|--beta)
            BETA="$optarg"
            ;;
        -a|--ratio)
            RATIO="$optarg"
            ;;
        -m|--memgb)
            MEMGB="$optarg"
            ;;
        -h|--help)
            showHelp
            exit 0
            ;;
        -v|--version)
            echo $VERSION
            exit 0
            ;;
        \?)
            exit 1
            ;;
    esac
done
shift $((OPTIND - 1))

# Perform Snakemake Workflow
snakemake -j $CORES --config input=$INPUT outdir=$OUTDIR \
rank_min=$RANK_MIN rank_max=$RANK_MAX \
lambda_min=$LAMBDA_MIN lambda_max=$LAMBDA_MAX trials=$TRIALS \
n_iter_max=$N_ITER_MAX x_new_list=$X_NEW_LIST \
input_sparse=$INPUT_SPARSE output_sparse=$OUTPUT_SPARSE \
x_new_sparse=$X_NEW_SPARSE w_new_sparse=$W_NEW_SPARSE \
bin_h=$BIN_H bin_w_new=$BIN_W_NEW \
beta=$BETA ratio=$RATIO --resources mem_gb=$MEMGB
