name: Docker Pull/Run (koki/sbsmtfcv_component)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
    check-component-job:
        name: run R and Python job
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: docker run (1/3)
              run: |
                  docker run --rm koki/sbsmtfcv_component:latest R -e "library('dcTensor'); library('nnTensor'); library('tidyverse')"
            - name: docker run (2/3)
              run: |
                  docker run --rm koki/sbsmtfcv_component:latest python3 -c "import snakemake; import sys; import numpy as np"
            - name: docker run (3/3)
              run: |
                  docker run --rm koki/sbsmtfcv_component:latest snakemake -v